<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251120042240 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE spool_brand (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, note TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE spool ADD spool_brand_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE spool ADD CONSTRAINT FK_F6851B98234C6762 FOREIGN KEY (spool_brand_id) REFERENCES spool_brand (id)');
        $this->addSql('CREATE INDEX IDX_F6851B98234C6762 ON spool (spool_brand_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE spool_brand');
        $this->addSql('ALTER TABLE spool DROP CONSTRAINT FK_F6851B98234C6762');
        $this->addSql('DROP INDEX IDX_F6851B98234C6762');
        $this->addSql('ALTER TABLE spool DROP spool_brand_id');
    }
}
